### ISSUE TITLE
Why this repo is Empty?

### ISSUE THREAD

**Issue by RomjanHossain** [AlifSakib/nextjs-latest#1]
:)

**Comment by AlifSakib** [comment]
🗡️ Well, you see, this repository is on a diet. It's having "code fasting" to achieve that sleek and slim look :p

**Comment by RomjanHossain** [comment]
> 🗡️ Well, you see, this repository is on a diet. It's having "code fasting" to achieve that sleek and slim look :p

i think you fad this repo with drug, instead of being fat, it became more slim
